- alias: 'Hannes Deckenlicht an'
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.pangea
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.meq0325581
- alias: 'Hannes Deckenlicht aus'
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.pangea
      from: 'on'
      to: 'off'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: switch.meq0325581
