- alias: 'Nachtkasterl_on_long'
  trigger:
    - platform: mqtt
      topic: hm/status/Schlafzimmer.Taster.oben/PRESS_LONG
    - platform: event
      event_type: homematic.keypress
      event_data:
        #name: Schlafzimmer.Taster
        name: NEQ1543071
        channel: 2
        param: PRESS_LONG
    - platform: event
      event_type: homematic.keypress
      event_data:
        name: Schlafzimmer.Taster
        channel: 2
        param: PRESS_LONG
  action:
    - service: light.turn_on
      data:
        entity_id: light.nachtkasterl
        #entity_id: light.fernsehlampe
        brightness: 255
        profile: relax

