switch.it_stecker_1:
  friendly_name: Wallpanel
  icon: mdi:earth
switch.it_2:
  friendly_name: Gelsenstecker
  icon: mdi:bug
switch.sleeping:
  icon: mdi:sleep
  friendly_name: schlafen
switch.vacation:
  icon: mdi:airplane
  friendly_name: Urlaub
switch.guests:
  icon: mdi:human-male-female
  friendly_name: "Gaeste anwesend"
switch.presence:
  icon: mdi:account-multiple
  friendly_name: Detect Presence
switch.alert_lueftung:
  icon: mdi:fan
  friendly_name: LÃ¼ftungsbenachrichtigung
switch.detect_motion:
  icon: mdi:walk
switch.nightlights:
  icon: mdi:weather-night
  friendly_name: Nachtlicht
switch.alert_motion:
  icon: mdi:walk
  friendly_name: "Alarmautomatik"
switch.nas:
  icon: mdi:harddisk
switch.ccu:
  icon: mdi:radar
switch.pangea:
  icon: mdi:desktop-tower
switch.heizsaison:
  icon: mdi:thermometer-lines
switch.wohnzimmer_tv:
  icon: mdi:television-classic
sensor.petsi_state:
  icon: mdi:roomba
switch.petsi_clean:
  icon: mdi:roomba
switch.petsi_dock:
  icon: mdi:roomba
switch.petsi_find:
  icon: mdi:music
