- platform: pushover
  name: hannes
  api_key: !secret HA_PUSHOVER_TOKEN
  user_key: !secret HA_PUSHOVER_HANNES
- platform: pushover
  name: barbara
  api_key: !secret HA_PUSHOVER_TOKEN
  user_key: !secret HA_PUSHOVER_BARBARA
- platform: pushover
  name: both
  api_key: !secret HA_PUSHOVER_TOKEN
  user_key: !secret HA_PUSHOVER_BOTH
- platform: slack
  name: slack
  api_key: !secret HA_SLACK_APIKEY
  default_channel: '#haus'
- name: browser
  platform: html5
  gcm_api_key: !secret HA_GCM_API_KEY
  gcm_sender_id: !secret HA_GCM_SENDER_ID
