---
entities:
  - binary_sensor.leq1085620_state
  - binary_sensor.meq0186547_state
  - binary_sensor.meq0186623_state
  - binary_sensor.meq0537387_motion
  - climate.meq0182097
  - light.barbara_tischlampe
  - light.it_stecker_3
  - light.p16tw_01
  - light.p16tw_02
  - media_player.kodi_hannes
  - sensor.meq0537387_brightness
  - switch.meq0325581
  - switch.pangea
  - media_player.buro
