---
cors_allowed_origins:
  - https://haus.cyberkov.at
  - https://haus.cyberkov.lan
ssl_certificate: !secret HA_HTTP_CERT
ssl_key: !secret HA_HTTP_KEY
base_url: haus.cyberkov.at
use_x_forwarded_for: true
api_password: !secret HA_HTTP_LOGIN
ip_ban_enabled: false
login_attempts_threshold: 3
trusted_networks:
  - 127.0.0.1
  - ::1
  - 172.17.0.0/24
  - 192.168.1.0/25
