---
#default: info
default: debug
logs:
  homeassistant.bootstrap: info
  homeassistant.components.device_tracker.ubus: warn
  homeassistant.components.device_tracker.nmap_tracker: warn
  homeassistant.components.homematic: info
  homeassistant.components.lightify: warn
  homeassistant.components.http: warn
  homeassistant.components.influxdb: fatal
  homeassistant.components.media_player: warn
  homeassistant.components.mqtt: info
  homeassistant.components.rfxtrx: warn
  homeassistant.components.sensor.mold_indicator: fatal
  homeassistant.components.sensor: warn
  homeassistant.components: info
  homeassistant.core: warn
  homeassistant.loader: warn
  openzwave: info
  pyhomematic: warn
  requests.packages.urllib3.connectionpool: warn
